import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ==============================================================================
# SCRIPT 07: POST-REGRESSION VISUALIZATIONS & THRESHOLD GRAPH
# ==============================================================================

INPUT_FILE = "data/cleaned/engineered_panel.csv"
DATA_FILE = "data/cleaned/threshold_graph_data.csv"
FIG_DIR = "results/figures"
os.makedirs(FIG_DIR, exist_ok=True)

plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({"font.family": "serif", "font.size": 11})

# ==============================================================================
# 1. THRESHOLD PROFILE GRAPH (FIGURE 2 IN MANUSCRIPT)
# ==============================================================================
print("Generating Figure 2: SSR Threshold Likelihood Profile...")
if os.path.exists(DATA_FILE):
    df_thresh = pd.read_csv(DATA_FILE)
    
    # Explicitly grab the baseline model variables generated by Stata
    plot_data = df_thresh[['rgm_gamma', 'rgm_lrofgamma']].dropna().drop_duplicates().sort_values(by='rgm_gamma')

    plt.figure(figsize=(10, 6))
    plt.plot(plot_data['rgm_gamma'], plot_data['rgm_lrofgamma'], color='#1f77b4', linewidth=1.5)
    plt.axhline(0, color='black', linewidth=0.8)

    plt.xlabel(r'Threshold Parameter ($\gamma = \ln$ GDP)', fontsize=12)
    plt.ylabel(r'Likelihood Ratio $LR(\gamma)$', fontsize=12)
    plt.title('') # Blank for LaTeX

    plt.tight_layout()
    plt.savefig(os.path.join(FIG_DIR, "real_ssr_profile.png"), dpi=300)
    plt.close()
    print("SUCCESS: Figure 2 saved directly to 'results/figures/real_ssr_profile.png'")
else:
    print(f"WARNING: File {DATA_FILE} not found. Please run Stata Script 06 first.")

# ==============================================================================
# 2. PRESENTATION GRAPHICS: REGIME CLASSIFICATION SCATTER
# ==============================================================================
print("Generating supplementary presentation graphics...")
df = pd.read_csv(INPUT_FILE)
GAMMA_OPT = 9.036818 # Extracted from Script 06 Stata output

plt.figure(figsize=(10, 6))
threshold_usd = int(round(np.exp(GAMMA_OPT), 0))
r1_label = f'Regime 1 (< ${threshold_usd:,})'
r2_label = f'Regime 2 (> ${threshold_usd:,})'

df['Regime'] = df['ln_gdp_per_capita'].apply(lambda x: r2_label if x > GAMMA_OPT else r1_label)

sns.scatterplot(data=df, x='ln_gdp_per_capita', y='ln_ef_prod', hue='Regime', 
                palette={r1_label: 'darkred', r2_label: 'navy'}, 
                alpha=0.7, s=80, edgecolor='white')

plt.axvline(x=GAMMA_OPT, color='black', linestyle='--', linewidth=2, label=r'Structural Break ($\gamma = %.3f$)' % GAMMA_OPT)
plt.xlabel("Natural Log of GDP per Capita")
plt.ylabel("Natural Log of Domestic Ecological Footprint")
plt.legend(loc='upper left', frameon=True)

plt.tight_layout()
plt.savefig(os.path.join(FIG_DIR, "regime_split_scatter.png"), dpi=300, bbox_inches="tight")
plt.close()
print("SUCCESS: Presentation scatter plot saved to 'results/figures/regime_split_scatter.png'")